export const emojiList = [
    { symbol: "🫡", message: "Saluting face" },
    { symbol: "😤", message: "Face with steam from nose" },
    { symbol: "😘", message: "Face throwing a kiss" },
    { symbol: "🌞", message: "Sun with face" },
    { symbol: "😷", message: "Face with medical mask" },
    { symbol: "😶", message: "Face without mouth" },
    { symbol: "🫣", message: "Face with peeking eye" },
    { symbol: "🤭", message: "Face with hand over mouth" },
    { symbol: "🫢", message: "Face with open eyes and hand over mouth" },
    { symbol: "😐", message: "Neutral face" },
    { symbol: "😵", message: "Face with crossed out eyes" },
    { symbol: "😮", message: "Face with open mouth" },
    { symbol: "😝", message: "Face with stuck-out tongue and tightly-closed eyes" },
    { symbol: "🤕", message: "Face with head bandage" },
    { symbol: "🧐", message: "Face with monocle" },
    { symbol: "😗", message: "Kissing face" },
    { symbol: "🫤", message: "Face with diagonal mouth" },
    { symbol: "🤨", message: "Face with raised eyebrow" },
    { symbol: "🐵", message: "Monkey face" },
    { symbol: "🙄", message: "Face with rolling eyes" },
    { symbol: "🙋", message: "Happy person raising one hand" },
    { symbol: "🤗", message: "Smiling face with open hands" },
    { symbol: "🙌", message: "Person raising both hands in celebration" },
    { symbol: "😌", message: "Relieved face" },
    { symbol: "😥", message: "Disappointed but relieved face" },
    { symbol: "☺️", message: "Smiling face" },
    { symbol: "😁", message: "Grinning face with smiling eyes" },
    { symbol: "😂", message: "Face with tears of joy" },
    { symbol: "😊", message: "Smiling face with smiling eyes" },
    { symbol: "😀", message: "Grinning face" },
    { symbol: "😎", message: "Smiling face with sunglasses" },
    { symbol: "😹", message: "Cat face with tears of joy" },
    { symbol: "☺", message: "White smiling face" },
    { symbol: "🙂", message: "Slightly smiling face" },
    { symbol: "🎉", message: "Party popper" },
    { symbol: "😍", message: "Smiling face with heart-shaped eyes" },
    { symbol: "😄", message: "Smiling face with open mouth and smiling eyes" },
    { symbol: "✌", message: "Victory hand" },
    { symbol: "🥰", message: "Smiling face with hearts" },
    { symbol: "👏", message: "Clapping hands sign" },
    { symbol: "👨", message: "Man" },
    { symbol: "🧍‍♂", message: "Man standing" },
    { symbol: "👨‍🎨", message: "Man artist" },
    { symbol: "👨‍🎓", message: "Man student" },
    { symbol: "🚶‍♂", message: "Man walking" },
    { symbol: "👨‍🦽", message: "Man in manual wheelchair" },
    { symbol: "👨‍🦯", message: "Man with white cane" },
    { symbol: "👱‍♂", message: "Man blond hair" },
    { symbol: "👨‍🔧", message: "Man mechanic" },
    { symbol: "👨‍🎤", message: "Man singer" },
    { symbol: "👨‍🔬", message: "Man scientist" },
    { symbol: "👨‍🦲", message: "Man bald" },
    { symbol: "👰‍♂", message: "Man with veil" },
    { symbol: "💂‍♂", message: "Man guard" },
    { symbol: "👨‍🏫", message: "Man teacher" },
    { symbol: "👨‍🌾", message: "Man farmer" },
    { symbol: "👨🏼‍🦽", message: "Man in manual wheelchair medium light skin tone" },
    { symbol: "👨‍⚖", message: "Man judge" },
    { symbol: "👨‍🦼", message: "Man in motorized wheelchair" },
    { symbol: "👨🏽‍🦽", message: "Man in manual wheelchair medium skin tone" },
    { symbol: "🧒", message: "Child" },
    { symbol: "👦", message: "Boy" },
    { symbol: "🧑‍🎓", message: "Student" },
    { symbol: "🚸", message: "Children crossing" },
    { symbol: "🧒🏻", message: "Child light skin tone" },
    { symbol: "🧒🏼", message: "Child medium light skin tone" },
    { symbol: "🧒🏾", message: "Child medium dark skin tone" },
    { symbol: "🧒🏽", message: "Child medium skin tone" },
    { symbol: "🚼", message: "Baby symbol" },
    { symbol: "👧", message: "Girl" },
    { symbol: "👶", message: "Baby" },
    { symbol: "🐤", message: "Baby chick" },
    { symbol: "🧒🏿", message: "Child dark skin tone" },
    { symbol: "👼", message: "Baby angel" },
    { symbol: "🧑🏼‍🍼", message: "Person feeding baby medium light skin tone" },
    { symbol: "👨🏼‍🍼", message: "Man feeding baby medium light skin tone" },
    { symbol: "🧑🏻‍🍼", message: "Person feeding baby light skin tone" },
    { symbol: "🧑🏽‍🍼", message: "Person feeding baby medium skin tone" },
    { symbol: "👨🏽‍🍼", message: "Man feeding baby medium skin tone" }
  ];